### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by shirase-aoi** [pine613/crystal-build#21]
OS is Cent OS 6.6
cloud service is SAKURA VPS

$ cat /etc/redhat-release 
CentOS release 6.6 (Final)

$ perl -v
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

$ crenv install -l
Available versions:
can't locate Archive/Tar.pm in @INC (@INC contains: /$HOME/.crenv/plugins/crystal-build/bin/../vendor/lib /$HOME/.crenv/plugins/crystal-build/bin/../lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /$HOME/.crenv/plugins/crystal-build/bin/../lib/Crenv/Utils.pm line 8.
BEGIN failed--compilation aborted at /$HOME/.crenv/plugins/crystal-build/bin/../lib/Crenv/Utils.pm line 8.
Compilation failed in require at /$HOME/.crenv/plugins/crystal-build/bin/../lib/Crenv.pm line 11.
BEGIN failed--compilation aborted at /$HOME/.crenv/plugins/crystal-build/bin/../lib/Crenv.pm line 11.
Compilation failed in require at /$HOME/.crenv/plugins/crystal-build/bin/crystal-build line 15.
BEGIN failed--compilation aborted at /$HOME/.crenv/plugins/crystal-build/bin/crystal-build line 15.

**Comment by pine613** [comment]
犯人は CentOS 6 だった。
http://d.hatena.ne.jp/perlcodesample/20120603/1339333786
